"""empty message

Revision ID: 2480e5c85e06
Revises: cf7e6721f0b3
Create Date: 2020-06-25 08:55:21.376439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2480e5c85e06'
down_revision = 'cf7e6721f0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###
