"""empty message

Revision ID: a1f4e1e2e3ea
Revises: 2480e5c85e06
Create Date: 2020-07-02 09:22:04.268383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f4e1e2e3ea'
down_revision = '2480e5c85e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'direccion')
    op.drop_table('empresa')
    # ### end Alembic commands ###
